- name: variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, Im learning {{COURSE}} which is {{DURATION}} and trainer is {{TRAINER}}"